### ISSUE TITLE
在自定义协议的页面中，缺少一个将修改的自定义协议应用于aeraki环境的步骤

### ISSUE THREAD

**Issue by hyqhyq3** [aeraki-mesh/website#27]
在自定义协议页面，有两个问题：
1. 找不到build.sh , 这个在提交历史中找到了。通过仓库的README，可以知道新的demo可以用make build进行构建，这个问题不大
2. 在文档中没有看到如何将编译出来的产物集成到aeraki中

**Comment by hyqhyq3** [comment]
我看到了，是在pod的定义中加上annotations sidecar.istio.io/proxyImage
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: brpc-echo-client
  labels:
    app: brpc-echo-client
spec:
  selector:
    matchLabels:
      app: brpc-echo-client
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/bootstrapOverride: aeraki-bootstrap-config
        sidecar.istio.io/proxyImage: aeraki/meta-protocol-proxy-debug:1.2.3
      labels:
        app: brpc-echo-client
    spec:
      containers:
        - name: brpc-echo-client
          image: smwyzi/brpc-demo:2022-0508-0
          command:
            - /usr/local/bin/echo_client
            - --server=brpc-echo-server:8000
          ports:
            - containerPort: 9009

```
